/*@StepGroupList
{
  "groups": []
}
*/

// ************************** IMPORTANT **************************
// This file is auto-generated by PlayQ for Step Group.
// Do not edit it manually. File is auto-generated.
// Any changes done directly will be lost on the next generation.
// ***************************************************************

import { Given } from '@cucumber/cucumber';


